<a href="https://colab.research.google.com/github/Abdullah5277/Deep-Learning/blob/main/Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.utils import to_categorical

In [ ]:
 pip install kagglehub panda

Requirement already satisfied: kagglehub in /usr/local/lib/python3.13/dist-packages (1.0.2)
Collecting panda
  Downloading panda-0.3.1.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.13/dist-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kagglehub) (26.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from panda) (80.10.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (2026.7.22)
Building wheels for collected packages: panda
  Building wheel for panda (setup.py) ... done
  Created wheel for panda: filename=panda-0.3.1-py3-none-any.whl size=7284 sha256=c88a12d86991cddb636e49dcb6d43422a0e8329ce1369d33d39679689a550a88
  Stored in directory: /root/.cache/pip/wheels/53/7c/f7/d3267739bc9dfdfc43724391337c9955e7d5b5830888d735e3
Successfully built panda
Installing collected packages: panda
Successfully installed panda-0.3.1

In [ ]:
# pip install kagglehub pandas
import kagglehub
import pandas as pd

path = kagglehub.dataset_download("oddrationale/mnist-in-csv")
print("Path to dataset files:", path)

df = pd.read_csv(f"{path}/mnist_train.csv")
df_test = pd.read_csv(f"{path}/mnist_test.csv")

print(df.shape) # (60000, 785)
print(df_test.shape) # (10000, 785)
df.head()

Using Colab cache for faster access to the 'mnist-in-csv' dataset.
Path to dataset files: /kaggle/input/mnist-in-csv
(60000, 785)
(10000, 785)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.columns

Index(['label', '1x1', '1x2', '1x3', '1x4', '1x5', '1x6', '1x7', '1x8', '1x9',
       ...
       '28x19', '28x20', '28x21', '28x22', '28x23', '28x24', '28x25', '28x26',
       '28x27', '28x28'],
      dtype='object', length=785)

In [ ]:
df.shape

(60000, 785)

In [ ]:
df.isnull().sum()

label    0
1x1      0
1x2      0
1x3      0
1x4      0
        ..
28x24    0
28x25    0
28x26    0
28x27    0
28x28    0
Length: 785, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to 28x28
dtypes: int64(785)
memory usage: 359.3 MB

In [ ]:
# preprocess data

X_train=df.drop('label',axis=1).values
y_train=df['label'].values

X_test=df_test.drop('label',axis=1).values
y_test=df_test['label']

In [ ]:
X_train=X_train.astype("float32")/255.0
y_train=y_train.astype("float32")/255.0

In [ ]:
X_train_img=X_train.reshape(-1,28,28)
X_test_img=X_test.reshape(-1,28,28)

In [ ]:
y_train_cat=to_categorical(y_train,10)
y_test_Cat=to_categorical(y_test,10)

In [ ]:
from sklearn import metrics
Perceptron=Sequential([
    Flatten(input_shape=(28,28)),
    Dense(10,activation="softmax")
])

Perceptron.compile(optimizer='sgd',loss="categorical_crossentropy",metrics=['accuracy'])

In [ ]:
history_percep=Perceptron.fit(X_train_img,y_train_cat,epochs=10,batch_size=32,validation_data=(X_test_img,y_test_Cat),verbose=2)

Epoch 1/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9995 - loss: 0.3520 - val_accuracy: 0.1207 - val_loss: 154.9540
Epoch 2/10
1875/1875 - 4s - 2ms/step - accuracy: 1.0000 - loss: 0.0398 - val_accuracy: 0.1171 - val_loss: 167.3911
Epoch 3/10
1875/1875 - 5s - 3ms/step - accuracy: 1.0000 - loss: 0.0218 - val_accuracy: 0.1145 - val_loss: 176.0500
Epoch 4/10
1875/1875 - 4s - 2ms/step - accuracy: 1.0000 - loss: 0.0150 - val_accuracy: 0.1135 - val_loss: 182.7211
Epoch 5/10
1875/1875 - 5s - 3ms/step - accuracy: 1.0000 - loss: 0.0114 - val_accuracy: 0.1098 - val_loss: 188.1587
Epoch 6/10
1875/1875 - 4s - 2ms/step - accuracy: 1.0000 - loss: 0.0093 - val_accuracy: 0.1098 - val_loss: 192.7482
Epoch 7/10
1875/1875 - 4s - 2ms/step - accuracy: 1.0000 - loss: 0.0078 - val_accuracy: 0.1093 - val_loss: 196.7175
Epoch 8/10
1875/1875 - 6s - 3ms/step - accuracy: 1.0000 - loss: 0.0067 - val_accuracy: 0.1088 - val_loss: 200.2310
Epoch 9/10
1875/1875 - 4s - 2ms/step - accuracy: 1.0000 - loss: 0.0059 - val_accuracy: 0.1081 - val_loss: 203.3814
Epoch 10/10
1875/1875 - 4s - 2ms/step - accuracy: 1.0000 - loss: 0.0052 - val_accuracy: 0.1074 - val_loss: 206.2316

In [ ]:
acc_percep=Perceptron.evaluate(X_test_img,y_test_Cat,verbose=0)[1]

In [ ]:
acc_percep

0.10740000009536743